version: 2.1
orbs:
  node: circleci/node@1.1.6
dependencies:
  pre:
    - npm install npm@latest -g
    - npm install angular-cli@latest -g
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: ng lint musicdb-app-angular
  test:
    executor:
      name: node/default
    steps:
       - checkout
       - node/with-cache:
          steps:
            - run: npm install
            - run: ng lint musicdb-app-angular
workflows:
    build-and-test:
      jobs:
        - build
        - test
