version: 2.1
orbs:
  node: circleci/node@1.1.6
dependencies:
  pre:
    - npm install npm@latest -g
    - npm install angular-cli@latest -g
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    executor:
      name: node/default
    steps:
      - run:
          name: TSlint
          command: npm run lint

workflows:
    build-and-test:
      jobs:
        - build
        - test
